baseURL = 'https://xelon-coder.github.io/Sirius14_Blog/'
languageCode = 'en-us'
title = 'Sirius14 Blog'
theme = 'PaperMod'
paginate = 5
pygmentsUseClasses = true
pygmentsCodeFences = true

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

googleAnalytics = "UA-123-45"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Sirius14 Blog"
description = "ExampleSite description"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Sirius14"
images = [ "/Sirius14_Blog/img/logo.png" ]
DateFormat = "January 2, 2006"

[params.assets]
  favicon = "/Sirius14_Blog/img/logo.png"
  favicon16x16 = "/Sirius14_Blog/img/logo.png"
  favicon32x32 = "/Sirius14_Blog/img/logo.png"
  apple_touch_icon = "/Sirius14_Blog/img/logo.png"
  safari_pinned_tab = "/Sirius14_Blog/img/logo.png"

  [params.label]
  text = "Home"
  icon = "/Sirius14_Blog/img/logo.png"
  iconHeight = 35

  [params.profileMode]
  enabled = true
  title = "Sirius14 Blog"
  subtitle = "Writeups & article"
  imageUrl = "/Sirius14_Blog/img/logo.png"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Who am I ?"
    url = "article/who-am-i/"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Sirius14 Blogs"
  Content = "Writeups & article"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/Xelon-coder"

  [[params.socialIcons]]
  name = "rootme"
  url = "https://www.root-me.org/Sirius14"

  [[params.socialIcons]]
  name = "discord"
  url = "https://discordapp.com/users/427092192880754691"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://xelon-coder.github.io/Sirius14_Blog/"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "Writeups"
name = "Writeups"
url = "/writeups/"
weight = 10

[[menu.main]]
identifier = "Article"
name = "Article"
url = "/article/"
weight = 20

[markup.highlight]
  codeFences = true
  guessSyntax = true
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  tabWidth = 4
  noClasses = false